config/routes.rb
Akbay::Application.routes.draw do

  get "countries/index", as: "ruut"

  root 'countries#index'

  get 'appointment/set_layout' => 'appointments#set_layout', as: "reach"

  scope "/:locale" do
    resources :appointments
  end

  post 'appointments/webmaster' => 'appointments#webmaster'

  

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  attr_accessor :bypass_humanizer

  include Humanizer
  require_human_on :create, :unless => :bypass_humanizer

  validates :firstname, presence: true
  validates :email, presence: true,
                    :length => { :within => 5..50 },
                    :format => { :with => /\A[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}\z/i }
  validates :phone, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :set_cache_headers

  protect_from_forgery with: :exception

  layout :detect_browser


  def brwsr
    if detect_browser == "mobile_application"
      @brwsr = "mobile"
      @brwsr
    end
  end

  helper_method :brwsr

  private
    MOBILE_BROWSERS = ["android", "ipod", "opera mini", "blackberry", "palm","hiptop","avantgo","plucker", "xiino","blazer","elaine", "windows ce; ppc;", "windows ce; smartphone;","windows ce; iemobile", "up.browser","up.link","mmp","symbian","smartphone", "midp","wap","vodafone","o2","pocket","kindle", "mobile","pda","psp","treo"]

  def detect_browser
     if request.headers["HTTP_USER_AGENT"].nil?
       return 'application'
     end
     layout = selected_layout
     return layout if layout
     agent = request.headers["HTTP_USER_AGENT"].downcase
     MOBILE_BROWSERS.each do |m|
       return "mobile_application" if agent.match(m)
     end
     return "application"
   end

   def selected_layout
     session.inspect # force session load
     if session.has_key? "layout"
       return (session["layout"] == "mobile") ?
         "mobile_application" : "application"
     end
     return nil
   end

  # for page refresh after browser back button press. I found it in Internet.
  def set_cache_headers
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
  end

end

app/controllers/appointments_controller.rb
=begin
when you scope a resource in routes:
 scope "/:locale" do
   resources :appointments
 end

you must put the following in the appointments controller
 def default_url_options(options={})
  { locale: I18n.locale }
 end

otherwise missing required keys: [:id] error occurs,
after you fill the form and submit
=end



class AppointmentsController < ApplicationController

  before_action :set_i18n, only: [:index, :new, :create, :new]
  # before_action :default_url_options, only: [:index, :new, :create, :new]
  # for default_url_options method before_action does not work

  def default_url_options(options={})
    if params[:locale]
     { locale: params[:locale] }
    else
      {}
    end
     # this method must return {} in else clause, otherwise error occurs
  end

  def index
    redirect_to new_appointment_path
  end

  def new
    # @lang = params[:locale]
    # I18n.locale = @lang.to_sym
    @appointment = Appointment.new
  end


  def create
    @lang = params[:lang]
    @appointment = Appointment.new(params_permit1)
    @appointment.change_humanizer_question(params[:appointment][:humanizer_question_id])
    if @appointment.save
      redirect_to @appointment
      Office.mail_office(@appointment).deliver
    else
      flash.now[:error] = I18n.t("err")
      render 'new'
    end

  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def webmaster
    params_permit2
    email = params[:email]
    message = params[:message]
    Webmaster.mail_webmaster(email, message).deliver
    render :nothing => true
  end


  def params_permit1
    params.require(:appointment).permit(:id, :firstname, :lastname, :email, :phone, :comments,
                  :complaints, :humanizer_answer, :humanizer_question_id, :date, :time, :bypass_humanizer)
  end

  def params_permit2
    params.permit(:email, :message)
  end

  def set_layout
    session["layout"] = (params[:mobile] == "1" ? "mobile" : "normal")
    puts "session[:layout]: " + session[:layout]
    redirect_to :controller => :countries, :action => "index"
  end

  private
    def set_i18n
      @lang = params[:locale]
      I18n.locale = @lang.to_sym
    end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def default_url_options(options={})
     if params[:locale]
      { locale: params[:locale] }
     else
       {}
     end
      # this method must return {} in else clause, otherwise error occurs
   end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/appointments/new.html.erb
<div class="image-health">
  <%= image_tag "img-health.jpg", class: "fit-image" %>
</div>

<div class="image-health2">
  <%= image_tag "img-health2.jpg", class: "fit-image" %>
</div>

<div class="main">

  <% if brwsr == "mobile" %>
      <ul class="f16">
        <% if @lang == "en" %>
            <% @lang = "us" %>
            <li class="flag <%= @lang %> flg_in_app_new" id="<%= @lang %>" title=""></li>
        <% elsif @lang == "zh-CN" %>
            <% @lang = "cn" %>
            <li class="flag <%= @lang %> flg_in_app_new" id="<%= @lang %>" title=""></li>
        <% else %>
            <li class="flag <%= @lang %> flg_in_app_new" id="<%= @lang %>" title=""></li>
        <% end %>
      </ul>
  <% else %>
      <ul class="f32">
        <% if @lang == "en" %>
            <% @lang = "us" %>
            <li class="flag <%= @lang %> flg_in_app_new" id="<%= @lang %>" title=""></li>
        <% elsif @lang == "zh-CN" %>
            <% @lang = "cn" %>
            <li class="flag <%= @lang %> flg_in_app_new" id="<%= @lang %>" title=""></li>
        <% else %>
            <li class="flag <%= @lang %> flg_in_app_new" id="<%= @lang %>" title=""></li>
        <% end %>
      </ul>
  <% end %>

  <div class="info">

    <h1 class="wlcm"><%= raw(t("welcome")) %></h1>

    <%= link_to t("register"), "#", class: "register" %> <br> <br>
    <%= link_to t("appointment"), "#", class: "app" %> <br> <br>
    <%= link_to t("comment"), "#", class: "cmnt" %> <br>
    <h4>Zorlu Center Teras Evler<br> T-1 Kat:3 No:128 <br> Zincirlikuyu 34340 <br> Beşiktaş / Istanbul / TURKEY </h4>
    <%= link_to "", class: "mp" do %>
      <%= image_tag "map.jpg", class:"mp_img" %>
    <% end %><br>
    <h4><%= image_tag("phone.jpg", size: "25x25") %> +90(212) 352-6464
      <br> <%= image_tag("cell.jpg", size: "25x25") %> +90(555) 978-3509 <br> FAX +90(212) 809-0252</h4>

  </div>

  <%= form_for @appointment do |f| %>

      <%= hidden_field_tag :lcl, @lang %>

      <%= f.hidden_field(:bypass_humanizer) %>

      <!--<input type="text" name="bypass_humanizer" id="bypass_humanizer">-->

      <!-- f.text_field :bypass_humanizer -->

      <% if @appointment.errors.any? %>
          <% flash.each do |name, msg| %>
              <% @msg = msg %>
          <% end %>
      <% end %>

      <div class="sign_up">
        <%= f.label t("firstname") %> <br>
        <!-- label_tag "appointment", t('firstname') -->
        <%= f.text_field :firstname, size: 22, class: 'fname' %> <span class="reqed">*</span> <br> <br>

        <%= f.label t("lastname") %> <br>
        <%= f.text_field :lastname, size: 22 %> <br> <br>

        <%= f.label t("email") %> <br>
        <%= email_field "appointment", "email", size: 22, class: "email" %> <span class="reqed">*</span> <br> <br>

        <%= f.label t("phone") %> <br>
        <%= phone_field "appointment", "phone", size: 22, class: 'phone' %> <span class="reqed">*</span> <br> <br>
      </div>


      <div class="comment">
        <%= f.label t("comment") %> <br>
        <%= f.text_area :comments, value: "", class: "comment", rows: "5", cols: "17" %> <span class="reqed">*</span> <br> <br>
      </div>

      <div class="appointment">
        <%= f.label t("complaint") %> <br>
        <%= f.text_area :complaints %> <br> <br>

        <%= f.label t("dt") %> <br>
        <%= f.text_field :date, size: 22, class: "calendr" %> <span class="reqed">*</span> <br ><br >

        <!--
        <f.date_select :date, default: 1.day.from_now, include: :blank %> <br> <br>
        -->

        <%= f.label t("tm") %> <br>
        <%= f.time_select :time, { prompt: true, minute_step: 15 } %> <span class="reqed">*</span><br> <br>
      </div>

      <div class="hmn">
        <%= f.label :humanizer_answer, @appointment.humanizer_question %> <br>
        <%= f.text_field :humanizer_answer, size: 22 %>
            <span class="reqed">* </span>
                <%= image_tag("refresh.jpg", class: "refresh") %>
            <br>
        <%= f.hidden_field :humanizer_question_id %>
      </div>

      <div class="sign_up">
        <%= f.submit "OK", class: "okey", id:'okey' %>
      </div>


  <% end %>

  <span class="err" style="color: red"><%= @msg %></span>

</div>


<%= form_tag("/appointments/webmaster", :method => "post", :id => 'webmaster') do %>

    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

    <input type="button" class="ex" value="X">

    <div class="field">
      <label for="email">Your Email:</label> <br>
      <input type="email" id="eml" name="email" size="22">
    </div>

    <div class="field">
      <label for="message">Message:</label> <br>
      <textarea id="msg" name="message" rows="5" cols="22" required="required"></textarea>
    </div>

    <div class="field">
      <%= label_tag :humanizer_answer, @appointment.humanizer_question %> <br>
      <%= text_field_tag :humanizer_answer,'', {size: 22, required: "required", class: "hmnzr_ans"} %>
        <%= image_tag("refresh.jpg", class: "refresh") %>
      <%= hidden_field_tag :humanizer_question_id %>
    </div>

    <div class="field">
      <button type="submit" id="send">OK</button>
      <input type="button" class="cancel" value="Cancel">
    </div>

<% end %>

<div id="map_canvas"></div>

<footer>
  <%= link_to "Webmaster", "#", class: "webmaster-contact-link" %>
</footer>

app/views/appointments/show.html.erb
<%= image_tag 'home.jpg', class: "home" %>

<div class="tnx-page">
    <div class="tnx">
      <%= t("thanks", locale: "en") %>
    </div>

    <div class="tnx">
      <%= t("thanks", locale: "de") %>
    </div>

    <div class="tnx">
      <%= t("thanks", locale: "fr") %>
    </div>

    <div class="tnx">
      <%= t("thanks", locale: "es") %>
    </div>

    <div class="tnx">
      <%= t("thanks", locale: "it") %>
    </div>

    <div class="tnx">
      <%= t("thanks", locale: "zh-CN") %>
    </div>

    <div class="tnx">
      <%= t("thanks", locale: "tr") %>
    </div>
</div>

<h3 class="addr-in-show">
  <%= link_to "", class: "mp" do %>
    <%= image_tag "map.jpg", class:"mp_img" %>
  <% end %>&nbsp;Zorlu Center Teras Evler T-1 Kat:3 No:128 Zincirlikuyu 34340 - Beşiktaş / Istanbul / TURKEY</h3>
<h3 class="comm-in-show"><%= image_tag("phone.jpg", size:"25x25") %> +90(212) 352-6464 &nbsp;&nbsp; <%= image_tag("cell.jpg", size:"25x25") %> +90(555) 978-3509 &nbsp;&nbsp; FAX +90(212) 809-0252</h3>




<%= form_tag("/appointments/webmaster", :method => "post", :id => 'webmaster') do %>

    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

    <input type="button" class="ex" value="X">

    <div class="field">
      <label for="email">Your Email:</label> <br>
      <input type="email" id="eml" name="email" size="22">
    </div>

    <div class="field">
      <label for="message">Message:</label> <br>
      <textarea id="msg" name="message" rows="5" cols="22" required="required"></textarea>
    </div>

    <div class="field">
      <%= label_tag :humanizer_answer, @appointment.humanizer_question %> <br>
      <%= text_field_tag :humanizer_answer,'', {size: 22, required: "required", class: "hmnzr_ans"} %>
        <%= image_tag("refresh.jpg", class: "refresh") %>
      <%= hidden_field_tag :humanizer_question_id %>
    </div>

    <div class="field">
      <button type="submit" id="send">OK</button>
      <input type="button" class="cancel" value="Cancel">
    </div>

<% end %>


<footer>
  <%= link_to "Webmaster", "#", class: "webmaster-contact-link" %>
</footer>

app/views/countries/index.html.erb
<div class="imgs">
     <%= image_tag "image1.jpg", alt: "Op. Dr. Seyfi Akbay", class: "img" %>
     <%= image_tag "image2.jpg", alt: "Op. Dr. Seyfi Akbay", class: "img" %>
     <%= image_tag "image3.jpg", alt: "Op. Dr. Seyfi Akbay", class: "img" %>
     <%= image_tag "image4.jpg", alt: "Op. Dr. Seyfi Akbay", class: "img" %>
</div>
<h1 class="name">Op. Dr. Seyfi Akbay</h1>

<div class="prof">
Plastik Cerrah - Chirurgien Plastique - Schönheitschirurg - Cirujano Plástico - Chirurgo Plastico - Plastic Surgeon - 整形外科醫生
</div>

<h3 class="adr">
        <%= link_to "", class: "mp" do %>
            <%= image_tag "map.jpg", class:"mp_img" %>
        <% end %>&nbsp;Zorlu Center Teras Evler T-1 Kat:3 No:128 Zincirlikuyu 34340 - Beşiktaş / Istanbul / TURKEY</h3>
<h3 class="fon"><%= image_tag("phone.jpg", size:"25x25") %> +90(212) 352-6464 &nbsp;&nbsp; <%= image_tag("cell.jpg", size:"25x25") %> +90(555) 978-3509&nbsp;&nbsp;  FAX +90(212) 809-0252</h3>
<br>

<ul class="f32">
  <li class="flag tr" id="tr" title=""></li>
  <li class="flag fr" id="fr" title=""></li>
  <li class="flag de" id="de" title=""></li>
  <li class="flag es" id="es" title=""></li>
  <li class="flag it" id="it" title=""></li>
  <li class="flag us" id="en" title=""></li>
  <li class="flag cn" id="zh-CN" title=""></li>
</ul>

<ul class="f16">
  <li class="flag tr" id="tr" title=""></li>
  <li class="flag fr" id="fr" title=""></li>
  <li class="flag de" id="de" title=""></li>
  <li class="flag es" id="es" title=""></li>
  <li class="flag it" id="it" title=""></li>
  <li class="flag us" id="en" title=""></li>
  <li class="flag cn" id="zh-CN" title=""></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title>Op. Dr. Seyfi Akbay</title>
  <%= favicon_link_tag('medicine.jpg', :class => "favicon") %>
  <script src="https://maps.googleapis.com/maps/api/js">
      google.maps.event.addDomListener(window, 'load', initialize);
  </script>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
    var lang = '<%= I18n.locale || 'en' %>';
  </script>
</head>
<body>

<%= link_to(reach_path(:mobile => "1")) do %>
    <%= image_tag 'ipad.jpg', size: "25x25", class: "media-image" %>
<% end %>

<%= yield %>


<div id="map_canvas"></div>


</body>
</html>

app/views/layouts/mobile_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta name="viewport" content="width=960, initial-scale=1, maximum-scale=1" />
  <title>Op. Dr. Seyfi Akbay</title>
  <%= favicon_link_tag('medicine.jpg', :class=>"favicon") %>
  <script src="https://maps.googleapis.com/maps/api/js">
      google.maps.event.addDomListener(window, 'load', initialize);
  </script>
  <%= stylesheet_link_tag "mobile", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
    var lang = '<%= I18n.locale || 'en' %>';
  </script>
</head>
<body>


<%= link_to( reach_path(:mobile => "0")) do %>
   <%= image_tag 'laptop.jpg', size:"16x16" , class: "media-image" %>
<% end %>


<%= yield %>


<div id="map_canvas"></div>


</body>
</html>

app/views/office/mail_office.text.erb
Hasta adi: <%= @firstname %>

Hasta soyadi: <%= @lastname %>

Email <%= @email %>

Yorum: <%= @comments.blank? ? "YOK" : @comments  %>

Sikayet: <%= @complaints.blank? ? "YOK" : @complaints  %>

Randevu Tarihi: <%= @date.blank? ? "YOK" : @date  %>

Randevu Saati: <%= @time.blank? ? "YOK" : @time.to_s(:time)  %>

app/views/webmaster/mail_webmaster.text.erb
An email from <%= @email %> sent

and the message is:
<%= @message %>